version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: stripe
    versions:
    - 5.29.0
    - 5.29.1
    - 5.30.0
    - 5.31.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: capybara
    versions:
    - 3.35.1
  - dependency-name: webpacker
    versions:
    - 5.2.1
